spring:
    datasource:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
        platform: h2
    jpa:
        database: H2
        show-sql: true
        generate-ddl: true
        hibernate:
            format_sql: true
            ddl-auto: create-drop
    h2:
        console:
          enabled: true
          path: /console